[package]
name = "maze-robot"
version = "0.1.0"
edition = "2024"

[features]
verbose = []

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.49", features = ["derive"] }
lalrpop-util = { version = "0.22.2", features = ["lexer", "unicode"] }
rstest = "0.26.1"

[build-dependencies]
lalrpop = "0.22.2"
