// TODO:
// - add location tracking! https://lalrpop.github.io/lalrpop/location_tracking.html

use nostd::{boxed::Box, string::String, prelude::ToString};

use crate::ds::List;

use super::ast::{Expr, Prog, Stmt};

grammar;

// TOKENS

match {
    // strings
    r"[a-zA-Z][a-zA-Z0-9_`~!@#$%^&*\-+\\':;<>,.?/]*" => Str,

    // numbers
    r"[0-9][0-9_]*" => Num,

    // commas
    "," => Comma,

    // bind
    "=" => Eq,

    // Parens
    "(" => OParen,
    ")" => CParen,

    // Brackets
    "[" => OBrkt,
    "]" => CBrkt,

    // empty rule to disable default empty rules on whitespace
    "" => {},
} else {
    // rule to tokenize newlines
    r"\n" => NewLine,

    // rules to skip other whitespace
    r" *" => {},
    r"\t*" => {},

    // // finally, use default rules for all other cases
    // _,
}


// GRAMMAR

/// A Program is a list of function definition statements.
pub Prog: Prog = <StmtList> => Prog::new(<>);

StmtList: List<Stmt> = {
    <s:Stmt> NewLine NewLine <l:StmtList> => List::cons(*s, l),
    <Stmt> => List::one(*<>),
};

/// A Statement is a function definition, binding a list of argument symbols &
/// an expression of those arguments to a symbol.
pub Stmt: Box<Stmt> = {
    // function statment
    <id:Sym> <args:ArgList> Eq <body:Expr> => Box::new(Stmt::new(&id, args, *body)),
    <id:Sym> Eq <body:Expr> => Box::new(Stmt::new(&id, List::empty(), *body)),
};

ArgList: List<String> = {
    <s:Sym> <l:ArgList> => List::cons(s, l),
    <Sym> => List::one(<>),
};

/// An Expression is either a list, function invocation, variable reference,
/// literal integer, or parenthetical expression.
pub Expr: Box<Expr> = {
    // list expression
    OBrkt <ListMembs> CBrkt => Box::new(Expr::List(<>)),
    OBrkt CBrkt => Box::new(Expr::List(List::empty())),

    // function expression
    <Sym> <Expr> => Box::new(Expr::Fun(<>)),

    // ref expression
    <Sym> => Box::new(Expr::Ref(<>)),

    // literal integer expression
    <Int> => Box::new(Expr::Num(<>)),

    // parenthetical expression
    OParen <Expr> CParen => <>,
};

ListMembs: List<Box<Expr>> = {
    <e:Expr> Comma <l:ListMembs> => List::cons(e, l),
    <Expr> Comma => List::one(<>),
    <Expr> => List::one(<>),
}

/// a symbol is an alphabetical char, followed by 0 or more alpha,
/// numeric, or special chars
Sym: String = Str => <>.to_string();

/// an integer of at least one digit followed by 0 or more digits and 0 or more `_` separators
Int: usize = Num => <>.replace('_', "").parse().unwrap();
