use std::str::FromStr;

use crate::util::List;

use super::ast::{Expr, Stmt};

grammar;

pub Stmt: Box<Stmt> = {
    // function statment
    // TODO: how to make functions variadic?
    <id:Sym> <args:ArgList> "=" <body:Expr> => Box::new(Stmt::new(id, args, body)),
    <id:Sym> "=" <body:Expr> => Box::new(Stmt::new(id, List::empty(), body)),
}

ArgList: List<String> = {
    <s:Sym> <l:ArgList> => List::cons(s, l),
    <Sym> => List::one(<>),
}

pub Expr: Box<Expr> = {
    // list expression
    "[" <ListMembs> "]" => Box::new(Expr::List(<>)),
    "[" "]" => Box::new(Expr::List(List::empty())),

    // function expression
    <Sym> <Expr> => Box::new(Expr::Fun(<>)),

    // ref expression
    <Sym> => Box::new(Expr::Ref(<>)),

    // literal integer expression
    <Int> => Box::new(Expr::Num(<>)),

    // parenthetical expression
    "(" <Expr> ")" => <>,
};

ListMembs: List<Box<Expr>> = {
    <e:Expr> "," <l:ListMembs> => List::cons(e, l),
    <Expr> "," => List::one(<>),
    <Expr> => List::one(<>),
}


// TOKENS

/// a symbol is an alphabetical char, followed by 0 or more alpha,
/// numeric, or special chars
Sym: String = r"[a-zA-Z][a-zA-Z0-9_`~!@#$%^&*\-+\\':;<>,.?/]*" => <>.to_string();

/// an integer of at least one digit followed by 0 or more digits and 0 or more `_` separators
Int: i32 = r"[0-9][0-9_]*" => i32::from_str(&<>.replace('_', "")).unwrap();
// ^ shorthand for the following:
//
// Int: i32 = <s:r"[0-9_]+"> => i32::from_str(s).unwrap();
